language: node_js

notifications:
  email:
  - yiminghe@gmail.com

node_js:
- 0.12

before_install:
- |
    if ! git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(\.md$)|(^(docs|examples))/'
    then
      echo "Only docs were updated, stopping build process."
      exit
    fi
    npm install mocha-phantomjs -g
    phantomjs --version
script:
- |
    if [ "$TEST_TYPE" = test ]; then
      npm test
    else
      npm run $TEST_TYPE
    fi
env:
  matrix:
  - TEST_TYPE=lint
  - TEST_TYPE=browser-test
  - TEST_TYPE=browser-test-cover
  - TEST_TYPE=saucelabs
  global:
    - secure: DgQ/TYnA6DoKj8a2Z5yPgLXQAB6Ws3i2KcUewZ0L2wUcyWyafVxvr80Ekl9murc1MB0cE7MarW9Z4ETMJd7XROf+0ba1KcUnx+lWDn60zmlXesvRGmaE6k41tjPYVb4aJRIWmdiocJuI0dL8VtBKBs720jYRswv2hQd1jVHmWkaAFzEPWzXadMcflacdDxih9VMrSP1hGp1KXAI51jJ3xzneCMnMDYaMJ+0FST+rfPiM3IqsBxLspjvbC+K/MSmzm+UmSS1XSJhUzbjHMboCWNmoEEdLFjvEbYaFGeC0OPuDmtbJ2zNzZ4L2CBxhpf5B+5+HcgVx6I8BHNVuyB658YhG6KLPg41rMbHjH7IhON4UFpCm/Hr4JaFvsydToGecYYIoS4nfWBfig2uzMK7ca7BccBMy0OuqbIcBrO7b0M2jNwmzox/bEcnnTqpTj5qIjpnATOqx8YDUKjop3rp20TtLPxM0i1NSvucevIIb8RAefChtuI/1FHxQwMOm/4YD7qfp5WT6wl2EQ9nEtnbbYNbQBzEuUDtep3OcBOor8yzbvU5Pu9UkPaIzndy8PiT64bCXXCetCUdV9aLMrsQUZPSc6A0sgvQWZuTxYirv4aJLgXXNjKAdOYUCLL6OcKM+/Rc9aMsoUJ7H4PA4hSy2dThPrQyjLgm2LCfRfMoEZSU=
    - secure: ExwGati4sJBnkMHW16SQdE/JYNuO9QsA6Acz2igIbB6jawPiFqQnnha9L9FQU8GjgNBXTl/PmmnBaF8/PKcLHHJH3pV9dMzV58a2QKQS4jQ1TCFz1XerpbvpK3sKqqpK1OF+MURIt5rvh5tkqFwM2tghk/KfNgiIL/gWW4WdUQ1NBi4NY/KTeF9Ewmt3spHqKcC7s/sXmGX+xkPFRwqqolAOCpqGY02na2dzXVfmH4Tas9b8Sw2tjn+Rr1Filfxuyg/y7oaW7nI7eWjlua0YYXTxNfMbEyIY7EH/lpMHd49eyxApfj/0OjQu6BCV+jy/+/eEy815J4YV7lKlN9qHlSvUplhcpGTkmGFfx421bMHDsRueogGxNHciNguM9remOJ/dZcnFklpJgMVlurzMAg0XO/xHue0Fff0CHuzzN42ZE/SNhXhAqraKJC723+xUuDToLbM9E/oAco2/BrAMGZcA6p7O4Q1Zb8DZRCIrCMPl4Ywfb6vPuZPhZF9Pr0i9RHx3wxhSYazDsHcIdE/UoO0tBT4sHRsl4peTCNDN+UpVVIY6i/GS1HFULjRegXM+u68/bgb9IV0Rg71UzXhO2+33DnZ2+Jlvw7G22uHD+nbe3uI9F/9BpFvjFth8OEsZMZA4E/hNwnnapYCvCDg+an0BlCIXTefODoXnhaNwrGo=


matrix:
  allow_failures:
  - env: "TEST_TYPE=saucelabs"